<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "kelas".
 *
 * @property integer $id
 * @property integer $member_id
 * @property string $start_date
 * @property integer $mso_class_id
 * @property integer $day
 *
 * @property \common\models\User $member
 * @property string $aliasModel
 */
abstract class Kelas extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'kelas';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['member_id', 'mso_class_id', 'day'], 'integer'],
            [['start_date'], 'string'],
            [['member_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\User::className(), 'targetAttribute' => ['member_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'member_id' => 'Member ID',
            'start_date' => 'Start Date',
            'mso_class_id' => 'Mso Class ID',
            'day' => 'Day',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMember()
    {
        return $this->hasOne(\common\models\User::className(), ['id' => 'member_id']);
    }




}
