<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "materi".
 *
 * @property integer $id
 * @property string $title
 * @property string $description
 * @property integer $mso_class_id
 * @property integer $day
 *
 * @property \common\models\MsoClass $msoClass
 * @property string $aliasModel
 */
abstract class Materi extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'materi';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['description'], 'string'],
            [['mso_class_id', 'day'], 'integer'],
            [['title'], 'string', 'max' => 255],
            [['mso_class_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\MsoClass::className(), 'targetAttribute' => ['mso_class_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'description' => 'Description',
            'mso_class_id' => 'Mso Class ID',
            'day' => 'Day',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMsoClass()
    {
        return $this->hasOne(\common\models\MsoClass::className(), ['id' => 'mso_class_id']);
    }




}
