<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "mso_class".
 *
 * @property integer $id
 * @property string $string
 * @property string $aliasModel
 */
abstract class MsoClass extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'mso_class';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['string'], 'string', 'max' => 100]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'string' => 'String',
        ];
    }




}
